### ISSUE TITLE
The downloaded version doesn't allow me to click the compile button.

### ISSUE THREAD

**Issue by LegendEag1e** [Dukweeno/Duckuino#112]
The compiler doesn't change the compile button from inactive when ducky script is inputted. 
The live version works fine, but the downloadable version doesn't work in any browser

**Comment by Nurrl** [comment]
Hello @LegendEag1e, thanks for reporting that issue,
unfortunately, this is due to **CORS**(cf. [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) for further reference, but this is quite complex to understand directly) policy in modern web browsers which prevents a script from loading a file from the local disk, so the project won't work when accessing the page with `file:///`.

Two options are offered to you if you still want to launch it locally:
- Spin up a webserver and place the files into it, this will allow the script to query the files. (Depending on your OS, if you have `php-cli` installed, you can run an HTTP server like so: `php -S 127.0.0.1:8080`.)
- Disable CORS on your browser, tho I don't know how to and don't recommend it, since it can lead to serious security problems.
